apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb-cluster.labels" . | nindent 4 }}
    {{- with .Values.cluster.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # Image configuration
  {{- if .Values.image.registry }}
  image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
  {{- else }}
  image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
  {{- end }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- with .Values.image.pullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Cluster configuration
  replicas: {{ .Values.cluster.replicas }}
  
  {{- if .Values.galera.enabled }}
  galera:
    enabled: true
    {{- with .Values.galera.primary }}
    primary:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.galera.sst }}
    sst: {{ . }}
    {{- end }}
    {{- with .Values.galera.replicaThreads }}
    replicaThreads: {{ . }}
    {{- end }}
    {{- with .Values.galera.agent }}
    agent:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.galera.recovery }}
    recovery:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.galera.initContainer }}
    initContainer:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.galera.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  # Database and user configuration
  {{- with .Values.database }}
  database: {{ . }}
  {{- end }}
  {{- with .Values.username }}
  username: {{ . }}
  {{- end }}

  # Password configuration
  {{- if .Values.rootPassword.generate }}
  rootPasswordSecretKeyRef:
    name: {{ include "mariadb-cluster.fullname" . }}-root-password
    key: password
    generate: true
  {{- else if .Values.rootPassword.existingSecret }}
  rootPasswordSecretKeyRef:
    name: {{ .Values.rootPassword.existingSecret.name }}
    key: {{ .Values.rootPassword.existingSecret.key }}
  {{- end }}

  {{- if .Values.userPassword.generate }}
  passwordSecretKeyRef:
    name: {{ include "mariadb-cluster.fullname" . }}-user-password
    key: password
    generate: true
  {{- else if .Values.userPassword.existingSecret }}
  passwordSecretKeyRef:
    name: {{ .Values.userPassword.existingSecret.name }}
    key: {{ .Values.userPassword.existingSecret.key }}
  {{- end }}

  # Storage configuration
  storage:
    size: {{ .Values.storage.size }}
    {{- with .Values.storage.storageClassName }}
    storageClassName: {{ . }}
    {{- end }}
    {{- with .Values.storage.accessModes }}
    accessModes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.storage.volumeClaimTemplate }}
    volumeClaimTemplate:
      {{- toYaml . | nindent 6 }}
    {{- end }}

  # Resource configuration
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Service configuration
  {{- if .Values.service.primary }}
  primaryService:
    type: {{ .Values.service.primary.type }}
    {{- with .Values.service.primary.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.service.primary.loadBalancerIP }}
    loadBalancerIP: {{ . }}
    {{- end }}
    {{- with .Values.service.primary.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- end }}

  {{- if .Values.service.secondary }}
  secondaryService:
    type: {{ .Values.service.secondary.type }}
    {{- with .Values.service.secondary.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.service.secondary.loadBalancerIP }}
    loadBalancerIP: {{ . }}
    {{- end }}
    {{- with .Values.service.secondary.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  {{- end }}

  service:
    type: {{ .Values.service.type }}
    {{- with .Values.service.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.service.loadBalancerIP }}
    loadBalancerIP: {{ . }}
    {{- end }}
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}

  # Connection configuration
  {{- if .Values.connection.enabled }}
  connection:
    secretName: {{ include "mariadb-cluster.fullname" . }}-connection
    {{- with .Values.connection.secretTemplate }}
    secretTemplate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.primaryConnection.enabled }}
  primaryConnection:
    secretName: {{ include "mariadb-cluster.fullname" . }}-primary-connection
    {{- with .Values.primaryConnection.secretTemplate }}
    secretTemplate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .Values.secondaryConnection.enabled }}
  secondaryConnection:
    secretName: {{ include "mariadb-cluster.fullname" . }}-secondary-connection
    {{- with .Values.secondaryConnection.secretTemplate }}
    secretTemplate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  # Configuration
  {{- if .Values.myCnf }}
  myCnf: |
    {{- .Values.myCnf | nindent 4 }}
  {{- end }}

  {{- with .Values.myCnfConfigMapKeyRef }}
  myCnfConfigMapKeyRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Update strategy
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Pod configuration
  {{- with .Values.podSecurityContext }}
  podSecurityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.serviceAccount }}
  serviceAccountName: {{ .name }}
  {{- end }}

  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Metrics and monitoring
  {{- if .Values.metrics.enabled }}
  metrics:
    enabled: true
    {{- if .Values.metrics.exporter.image }}
    exporter:
      image: {{ .Values.metrics.exporter.image.registry }}/{{ .Values.metrics.exporter.image.repository }}:{{ .Values.metrics.exporter.image.tag }}
      {{- with .Values.metrics.exporter.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.exporter.port }}
      port: {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.metrics.passwordSecretKeyRef.generate }}
    passwordSecretKeyRef:
      name: {{ include "mariadb-cluster.fullname" . }}-metrics-password
      key: password
      generate: true
    {{- else if .Values.metrics.passwordSecretKeyRef.existingSecret }}
    passwordSecretKeyRef:
      name: {{ .Values.metrics.passwordSecretKeyRef.existingSecret.name }}
      key: {{ .Values.metrics.passwordSecretKeyRef.existingSecret.key }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.enabled }}
    serviceMonitor:
      enabled: true
      {{- with .Values.metrics.serviceMonitor.prometheusRelease }}
      prometheusRelease: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.additionalLabels }}
      additionalLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}

  # Environment variables
  {{- with .Values.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.envFrom }}
  envFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Volume mounts
  {{- with .Values.volumeMounts }}
  volumeMounts:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Volumes  
  {{- with .Values.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Initialization
  {{- if .Values.initContainers }}
  initContainers:
    {{- toYaml .Values.initContainers | nindent 4 }}
  {{- end }}

  {{- if .Values.sidecarContainers }}
  sidecarContainers:
    {{- toYaml .Values.sidecarContainers | nindent 4 }}
  {{- end }}